site_name: The Oval Table - Oil Price Prediction

nav:
  - Introduction: index.md
  - About:
      - 'Getting Started': 'about/getting-started.md'
      - 'Project Requirements': 'about/project-requirements.md'
      - 'License': 'about/license.md'
      - 'Release Notes': 'about/release-notes.md'
      - 'Changelog': 'about/changelog.md'
  - Data:
      - 'About the Data': 'data/about-data.md'
      - 'Variables': 'data/variables.md'
  - Web Interface:
      - 'Purpose': 'web-interface/purpose.md'
      - 'Endpoints': 'web-interface/endpoints.md'
      - 'Features': 'web-interface/features.md'
      - 'Web Interface Process': 'web-interface/process.md'
      - 'User Guide': 'web-interface/user-guide.md'
  - Models:
        - 'Models Overview': 'models/overview.md'
        - 'Model Performance': 'models/model-performance.md'
        - 'Cross Validation': 'models/cross-validation.md'
        - 'XGBoost': 'models/xgboost.md'
        - 'Random Forest': 'models/random-forest.md'
        - 'Polynomial Regression': 'models/polynomial-regression.md'
        - 'Naive Model': 'models/naive.md'
        - 'ARIMA': 'models/arima.md'
        - 'Prophet': 'models/prophet.md'
  - Design: design.md
  - Challenges: challenges.md
  - Conclusions: conclusions.md
  - FAQ: faq.md
  - Acknowledgements: acknowledgements.md
  - References: references.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  custom_dir: docs/overrides
  features:
    - navigation.top
    - navigation.footer

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      toc_depth: 4

